spring:
  application:
    name: gestionimmo  # Nom du microservice, utilisé par le Config-Service pour récupérer les configurations spécifiques

  config:
    import: configserver:http://localhost:9999  # URL obligatoire du Config-Service

logging:
  level:
    root: INFO
    com.sodeca.gestionimmo: DEBUG  # Niveau de log pour le package spécifique
  file:
    name: logs/application.log  # Fichier log principal
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5  # Envoi d'un heartbeat toutes les 5 secondes
    lease-expiration-duration-in-seconds: 10  # Eureka considère le service comme down après 10 secondes sans heartbeat
  client:
    healthcheck:
      enabled: true  # Active les checks de santé pour que Eureka détecte l'état réel du service

